### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by vitorbaptista** [kucherenko/strapi-plugin-passwordless#17]
Hi,

Thanks for your work on this plugin -- it has been very helpful for us.

For the last few weeks, we've been trying to chase a bug where new login tokens were invalid. It seemed random, we couldn't figure out why.

I think this issue was fixed by https://github.com/kucherenko/strapi-plugin-passwordless/pull/13. I just deployed it installing directly from GitHub, so we're unsure if it actually fixed the error, but it seems likely :pray: 

When you have some time, could you release a new bugfix release? We're probably not the only ones facing this issue, so it might save people time going down these rabbit holes.

Thank you!

**Comment by kucherenko** [comment]
strapi-plugin-passwordless@4.0.9 released from current main branch
