### ISSUE TITLE
Unauthorized error and not showind plugin on live.

### ISSUE THREAD

**Issue by SafaLabash** [kucherenko/strapi-plugin-passwordless#24]
Hello,i am trying to add the plugin.On localhost i can see the plugin and configure it .When i try to execute the request it returns error
POST http://localhost:1337/api/passwordless/send-link
body:{
  "email": "safi_981@abv.bg",
  "username":"safi_981"
}
 response: {
    "data": null,
    "error": {
        "status": 400,
        "name": "Error",
        "message": "Unauthorized",
        "details": {}
    }
}

When i send username and email,a new user is created but no token returned.Same with already created ones.When i deploy the changes,plugin is not visible.I can see it only localhost.

**Comment by kucherenko** [comment]
Thank you for the issue, could you please provide information about the version of the plugin and strapi?

**Comment by rihards-simanovics** [comment]
Hey @kucherenko I have the same issue here are the package dependencies and their versions in case you find this helpful:

```json
"dependencies": {
    "@sklinet/strapi-plugin-tinymce": "^1.0.6",
    "@strapi/plugin-graphql": "^4.7.1",
    "@strapi/plugin-i18n": "4.12.5",
    "@strapi/plugin-seo": "^1.8.0",
    "@strapi/plugin-users-permissions": "4.12.5",
    "@strapi/provider-email-nodemailer": "^4.7.0",
    "@strapi/strapi": "4.12.5",
    "better-sqlite3": "8.0.1",
    "delve": "^0.3.2",
    "patch-package": "^7.0.0",
    "postinstall-postinstall": "^2.1.0",
    "strapi-plugin-config-sync": "^1.1.1",
    "strapi-plugin-ezforms": "^0.1.5",
    "strapi-plugin-menus": "^1.3.1",
    "strapi-plugin-passwordless": "^4.0.13",
    "strapi-plugin-sitemap": "^2.0.11"
}
```

**Update**:
Hey quick update, it looks like my local dev env had no SMTP settings and due to it the registration kept failing, the error is supper weird though, unless you know the meaning it's hard to know what it means...
