### ISSUE TITLE
add option to keep token valid

### ISSUE THREAD

**Issue by yanicklandry** [kucherenko/strapi-plugin-passwordless#26]

**Comment by yanicklandry** [comment]
if you want to use it before my PR gets accepted:

```npm i https://github.com/yanicklandry/strapi-plugin-passwordless.git\#feature/26-add-option-to-keep-token-valid```

**Comment by kucherenko** [comment]
strapi-plugin-passwordless 4.0.14 published 🎉

your changes are here
