### ISSUE TITLE
Unable to save changes

### ISSUE THREAD

**Issue by BayBreezy** [kucherenko/strapi-plugin-passwordless#28]
Hello,

After updating the settings the Save button stays disabled. I am not able to click it to save the changes.

![image](https://github.com/kucherenko/strapi-plugin-passwordless/assets/53905713/29b759e7-1fa8-48d8-bc72-c189c9e28df2)

**Comment by kucherenko** [comment]
Thank you for the issue, will analyze it

**Comment by Aziaev** [comment]
same issue using 4.0.14

**Comment by vinikatyal** [comment]
Same issue what to do?

**Comment by BayBreezy** [comment]
@vinikatyal You have to just use the version before the latest one for now. I dont know react enough to create a PR for this. So until @kucherenko gets a chance to make the changes... we are just doomed

**Comment by vinikatyal** [comment]
> @vinikatyal You have to just use the version before the latest one for now. I dont know react enough to create a PR for this. So until @kucherenko gets a chance to make the changes... we are just doomed

Let me look at his code. I know react. Am new to strapi

**Comment by AnalyteSoftware** [comment]
@BayBreezy have you managed to get it working with 4.0.13?

**Comment by BayBreezy** [comment]
@AnalyteSoftware Yes, it works in that version. It stopped working when I update to the latest which is 4.0.14

**Comment by BayBreezy** [comment]
Any plans in place to fix this? 👀 @kucherenko

**Comment by kucherenko** [comment]
Hi!
The issue has been fixed!

strapi-plugin-passwordless 4.0.15 published 🎉

**Comment by BayBreezy** [comment]
Thank you @kucherenko
