### ISSUE TITLE
Endpoints look different from those shown in the readme

### ISSUE THREAD

**Issue by shumiyao** [kucherenko/strapi-plugin-passwordless#3]
I am using Strapi v. 4.0.5 and my endpoints becomes as follows, which does not look like those in the README.

| Method | Path |
| ------------- | ------------- |
| HEAD/GET  | /api/passwordless/passwordless/login  |
| POST | /api/passwordless/passwordless/send-link |

Is that how it is supposed to be or am I missing something?

**Comment by kucherenko** [comment]
The README has updated
